#!/bin/bash

set -e

EXERCISES_DIR=exercises
DEMOS_DIR=demos
CGAL_DIR=CGAL-3.8

command_test() {
        command -v $1 >/dev/null 2>&1
}

command_test qmake-qt4 && QMAKE=qmake-qt4 || QMAKE=qmake

build() {
	for d in $1/*; do
		[ ! -f $d/example.pro ] && continue
		echo " == Building $d"
		pushd $d >/dev/null
		$QMAKE
		make
		popd >/dev/null
	done
}

if [ ! -f bin/libgeoc.so ]; then
	pushd $CGAL_DIR >/dev/null
	cmake .
	make -j4
	popd >/dev/null

	$QMAKE CONFIG=release -o Release.mk

	mkdir -p Release
	make -f Release.mk -j4
fi

build $EXERCISES_DIR

build $DEMOS_DIR

build $DEMOS_DIR/make_grid
