#!/bin/bash

set -e

EXERCISES_DIR=exercises
DEMOS_DIR=demos
CGAL_DIR=CGAL-3.8

command_test() {
        command -v $1 >/dev/null 2>&1
}

command_test qmake-qt4 && QMAKE=qmake-qt4 || QMAKE=qmake

function build {
	for d in $1/*; do
		pushd $d
		$QMAKE
		make
		popd
	done
}

if [ ! -f bin/libgeoc.so ]; then
	pushd $CGAL_DIR
	cmake .
	make -j4
	popd

	$QMAKE CONFIG=release -o Release.mk

	mkdir -p Release
	make -f Release.mk
fi

build $EXERCISES_DIR

build $DEMOS_DIR

build $DEMOS_DIR/make_grid
