#!/bin/bash

set -e

EXERCISES_DIR=exercises
DEMOS_DIR=demos
CGAL_DIR=CGAL-3.8

command_test() {
        command -v $1 >/dev/null 2>&1
}

command_test qmake-qt4 && QMAKE=qmake-qt4 || QMAKE=qmake

function build {
	for d in $1/*; do
		pushd $d
		$QMAKE
		make
		popd
	done
}

echo "Compiling CGAL"
pushd $CGAL_DIR
cmake .
make
popd

$QMAKE CONFIG=release -o Release.mk

echo "Making initial library build"
mkdir -p Release
make -f Release.mk

echo "Compiling exercises"
build $EXERCISES_DIR

echo "Compiling demos"
build $DEMOS_DIR

echo "Compiling additional demos"
build $DEMOS_DIR/make_grid
